package com.example.learning_system_spring.infrastructure.exception;

public enum ErrorCode {
    INVALID_EMAIL,
    EMAIL_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    ROLE_NOT_FOUND,
    COURSE_NOT_FOUND,
    COURSE_NOT_PUBLISHED,
    COURSE_PRICE_LOCKED,
    COURSE_ALREADY_PUBLISHED,
    ACCESS_DENIED,
    BAD_REQUEST,
    SECTION_NOT_FOUND,
    SECTION_ACCESS_DENIED,
    LESSON_NOT_FOUND,
    LESSON_ACCESS_DENIED,
    // Voucher
    VOUCHER_NOT_FOUND,
    VOUCHER_INACTIVE,
    VOUCHER_NOT_YET_ACTIVE,
    VOUCHER_EXPIRED,
    VOUCHER_NOT_APPLICABLE,
    VOUCHER_MIN_ORDER_NOT_MET,
    VOUCHER_USAGE_LIMIT_REACHED,
    VOUCHER_USAGE_PER_USER_EXCEEDED,
    VOUCHER_USE_DENIED,
    VOUCHER_CODE_ALREADY_EXISTS,
    VOUCHER_USAGE_LIMIT_TOO_LOW,
    VOUCHER_IMMUTABLE_FIELD,
    // Purchase
    ALREADY_ENROLLED,
    INSUFFICIENT_BALANCE
}
